image: python:3.6.0

stages:
  - test



before_script:
  - apt-get update -yqq
  - apt-get install sqlite3 libsqlite3-dev -yqq
  - sqlite3 app/test.db
  - python3 -m venv env
  - source env/bin/activate
  - pip install -r requirements.txt




unit_test:
  stage: test
  allow_failure: true
  script:
  - PYTHONPATH=. pytest -v 
